name: Build if pushed or merged

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Build for linux/amd64
        run: docker run -e GOOS=linux -e GOARCH=amd64 -e HOME=/tmp -u 1000:1000 -v $(pwd):/go/src/app -w /go/src/app -it golang:rc bash -c 'go build -buildmode exe -o bin/main-${GOOS}-${GOARCH} ./cmd/main'
      - name: List go compoment
        run: 'ls -l *'
